"""
Generate GEM-format CSV verification tables from Fortran reference output.
==========================================================================
Reads benchmark/bs24_fortran_output.csv (generated by bs24_runner.f calling
Jeff Bayless's bs24_gmm.f) and reformats it into the GEM hazardlib CSV format
for submission to the OpenQuake engine test suite.

Using the Fortran as the reference ensures the GEM verification data is
independent of the Python implementation.

Usage (run from repo root):
    python tests/generate_gem_test_files.py

Requires:
    benchmark/bs24_fortran_output.csv  (generated by ./bs24_run in benchmark/)

Outputs:
    tests/data/BS24_CRATONIC.csv
    tests/data/BS24_NONCRATONIC.csv
    tests/bayless_somerville_2024_test.py

GEM CSV format:
    rup_*       : rupture parameters
    dist_*      : distance parameters
    site_*      : site parameters
    result_type : MEAN | TOTAL_STDDEV | INTER_EVENT_STDDEV | INTRA_EVENT_STDDEV
    damping     : 5
    PGA, SA(T)  : values in ln(g) for MEAN, ln units for stddevs

Unit conversion:
    Fortran outputs ln(cm/s/s). GEM expects ln(g).
    ln(g) = ln(cm/s/s) - ln(980.665) = ln(cm/s/s) - 6.89
"""
import os
import sys
import numpy as np
import pandas as pd

# -----------------------------------------------------------------------
# Paths
# -----------------------------------------------------------------------
REPO_ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
FORT_CSV  = os.path.join(REPO_ROOT, 'benchmark', 'bs24_fortran_output.csv')
DATA_DIR  = os.path.join(REPO_ROOT, 'tests', 'data')
TESTS_DIR = os.path.join(REPO_ROOT, 'tests')

LN_G_TO_CMSS = 6.89  # ln(980.665) — Fortran adds this, we subtract it

# GEM IMT columns — subset of periods in the Fortran output
IMT_PERIODS = [0.010, 0.100, 0.200, 0.500, 1.000, 2.000, 3.000, 5.000, 10.000]
IMT_COLS    = ['PGA', 'SA(0.1)', 'SA(0.2)', 'SA(0.5)', 'SA(1.0)',
               'SA(2.0)', 'SA(3.0)', 'SA(5.0)', 'SA(10.0)']
# Note: PGA in GEM format corresponds to T=0.01 sec in the Fortran
# (Fortran uses pgat=0.01 for the PGA computation)

# Fixed rupture geometry used in the runner (footwall)
DIP      = 45.0
RAKE     = 90.0
WIDTH    = 15.0
RY0      = 0.0


# -----------------------------------------------------------------------
# Load Fortran output
# -----------------------------------------------------------------------
def load_fortran(path):
    df = pd.read_csv(path, skipinitialspace=True)
    df['lnY_g'] = df['lnY_cmss'] - LN_G_TO_CMSS
    return df


# -----------------------------------------------------------------------
# Build GEM CSV for one tectonic class (CratFlag = 1 or 0)
# -----------------------------------------------------------------------
def build_gem_csv(df, crat_flag):
    sub = df[df['CratFlag'] == crat_flag].copy()

    scenario_cols = ['mag', 'rrup', 'vs30', 'ztor']
    scenarios = sub[scenario_cols].drop_duplicates().reset_index(drop=True)

    rows = []

    for _, sc in scenarios.iterrows():
        mag  = sc['mag']
        rrup = sc['rrup']
        vs30 = sc['vs30']
        ztor = sc['ztor']

        sc_data = sub[
            (np.isclose(sub['mag'],  mag,  atol=0.01)) &
            (np.isclose(sub['rrup'], rrup, atol=0.1))  &
            (np.isclose(sub['vs30'], vs30, atol=1.))   &
            (np.isclose(sub['ztor'], ztor, atol=0.1))
        ].copy()

        base = {
            'rup_mag':    mag,
            'rup_dip':    DIP,
            'rup_rake':   RAKE,
            'rup_ztor':   ztor,
            'rup_width':  WIDTH,
            'dist_rrup':  rrup,
            'dist_rjb':   rrup,
            'dist_rx':    -rrup,   # footwall
            'dist_ry0':   RY0,
            'site_vs30':  vs30,
            'site_z1pt0': -999.0,  # no basin term
            'damping':    5,
        }

        mean_vals  = {}
        sigma_vals = {}
        tau_vals   = {}
        phi_vals   = {}

        for imt_col, period in zip(IMT_COLS, IMT_PERIODS):
            row_p = sc_data[np.isclose(sc_data['period'], period, atol=0.001)]
            if row_p.empty:
                mean_vals[imt_col]  = np.nan
                sigma_vals[imt_col] = np.nan
                tau_vals[imt_col]   = np.nan
                phi_vals[imt_col]   = np.nan
            else:
                mean_vals[imt_col]  = round(float(row_p['lnY_g'].iloc[0]),  6)
                sigma_vals[imt_col] = round(float(row_p['sigma'].iloc[0]),   6)
                tau_vals[imt_col]   = round(float(row_p['tau'].iloc[0]),     6)
                phi_vals[imt_col]   = round(float(row_p['phi'].iloc[0]),     6)

        for result_type, vals in [
            ('MEAN',               mean_vals),
            ('TOTAL_STDDEV',       sigma_vals),
            ('INTER_EVENT_STDDEV', tau_vals),
            ('INTRA_EVENT_STDDEV', phi_vals),
        ]:
            row = dict(base)
            row['result_type'] = result_type
            row.update(vals)
            rows.append(row)

    col_order = (
        ['rup_mag', 'rup_dip', 'rup_rake', 'rup_ztor', 'rup_width',
         'dist_rrup', 'dist_rjb', 'dist_rx', 'dist_ry0',
         'site_vs30', 'site_z1pt0', 'result_type', 'damping'] + IMT_COLS
    )
    return pd.DataFrame(rows)[col_order]


# -----------------------------------------------------------------------
# Main
# -----------------------------------------------------------------------
if __name__ == '__main__':
    print(f"Reading Fortran output from: {FORT_CSV}")
    if not os.path.exists(FORT_CSV):
        print("ERROR: Fortran CSV not found.")
        print("Run ./bs24_run in the benchmark/ folder first.")
        sys.exit(1)

    df = load_fortran(FORT_CSV)
    print(f"  {len(df)} rows loaded")
    print(f"  Mags:    {sorted(df.mag.unique())}")
    print(f"  Rrup:    {sorted(df.rrup.unique())}")
    print(f"  Vs30:    {sorted(df.vs30.unique())}")
    print(f"  Ztor:    {sorted(df.ztor.unique())}")
    print(f"  Periods: {len(df.period.unique())} unique")

    os.makedirs(DATA_DIR, exist_ok=True)

    print("\nBuilding BS24_CRATONIC.csv...")
    df_c = build_gem_csv(df, crat_flag=1)
    out_c = os.path.join(DATA_DIR, 'BS24_CRATONIC.csv')
    df_c.to_csv(out_c, index=False, float_format='%.6f')
    print(f"  Written: {out_c}  ({len(df_c)} rows, "
          f"{len(df_c)//4} scenarios x 4 result types)")

    print("Building BS24_NONCRATONIC.csv...")
    df_nc = build_gem_csv(df, crat_flag=0)
    out_nc = os.path.join(DATA_DIR, 'BS24_NONCRATONIC.csv')
    df_nc.to_csv(out_nc, index=False, float_format='%.6f')
    print(f"  Written: {out_nc}  ({len(df_nc)} rows, "
          f"{len(df_nc)//4} scenarios x 4 result types)")

    # -----------------------------------------------------------------------
    # Generate GEM test module
    # -----------------------------------------------------------------------
    test_code = ('# -*- coding: utf-8 -*-\n'
'"""\n'
'GEM-style verification tests for the Bayless and Somerville (2024) GMM.\n'
'\n'
'Reference values in the CSV files were computed from the Fortran reference\n'
'subroutine bs24_gmm.f (provided by Jeff Bayless, jeff.bayless@aecom.com),\n'
'not from the Python implementation itself. This ensures the test data is\n'
'truly independent of the code being tested.\n'
'\n'
'Agreement between Fortran and Python: max difference 0.000045 ln units on\n'
'mean SA, 0.000005 ln units on sigma, across 14,256 test cases.\n'
'\n'
'Place the CSV files at:\n'
'    openquake/hazardlib/tests/gsim/data/BS24/BS24_CRATONIC.csv\n'
'    openquake/hazardlib/tests/gsim/data/BS24/BS24_NONCRATONIC.csv\n'
'\n'
'Author: Thuany Costa de Lima, Geoscience Australia (May 2026)\n'
'"""\n'
'import unittest\n'
'\n'
'from openquake.hazardlib.gsim.bayless_somerville_2024 import (\n'
'    BaylessSomerville2024Cratonic,\n'
'    BaylessSomerville2024NonCratonic,\n'
')\n'
'from openquake.hazardlib.tests.gsim.utils import BaseGSIMTestCase\n'
'\n'
'\n'
'class BaylessSomerville2024CratonicTestCase(BaseGSIMTestCase):\n'
'    """\n'
'    Verification tests for the Cratonic version of BS24.\n'
'    Applicable to Yilgarn, Gawler, Pilbara, Kimberley, and Northern\n'
'    Australian Cratons (NSHA23 Precambrian classification).\n'
'    """\n'
'    GSIM_CLASS = BaylessSomerville2024Cratonic\n'
'\n'
'    def test_mean(self):\n'
'        self.check(\'BS24/BS24_CRATONIC.csv\', max_discrep_percentage=0.1)\n'
'\n'
'    def test_std_total(self):\n'
'        self.check(\'BS24/BS24_CRATONIC.csv\', max_discrep_percentage=0.1)\n'
'\n'
'    def test_std_inter(self):\n'
'        self.check(\'BS24/BS24_CRATONIC.csv\', max_discrep_percentage=0.1)\n'
'\n'
'    def test_std_intra(self):\n'
'        self.check(\'BS24/BS24_CRATONIC.csv\', max_discrep_percentage=0.1)\n'
'\n'
'\n'
'class BaylessSomerville2024NonCratonicTestCase(BaseGSIMTestCase):\n'
'    """\n'
'    Verification tests for the NonCratonic version of BS24.\n'
'    Applicable to Eastern Australian Phanerozoic Accretionary Terranes,\n'
'    extended and oceanic crust (NSHA23 Phanerozoic classification).\n'
'    """\n'
'    GSIM_CLASS = BaylessSomerville2024NonCratonic\n'
'\n'
'    def test_mean(self):\n'
'        self.check(\'BS24/BS24_NONCRATONIC.csv\', max_discrep_percentage=0.1)\n'
'\n'
'    def test_std_total(self):\n'
'        self.check(\'BS24/BS24_NONCRATONIC.csv\', max_discrep_percentage=0.1)\n'
'\n'
'    def test_std_inter(self):\n'
'        self.check(\'BS24/BS24_NONCRATONIC.csv\', max_discrep_percentage=0.1)\n'
'\n'
'    def test_std_intra(self):\n'
'        self.check(\'BS24/BS24_NONCRATONIC.csv\', max_discrep_percentage=0.1)\n'
'\n'
'\n'
'if __name__ == \'__main__\':\n'
'    unittest.main()\n')

    test_out = os.path.join(TESTS_DIR, 'bayless_somerville_2024_test.py')
    with open(test_out, 'w') as f:
        f.write(test_code)
    print(f"\nWritten: {test_out}")

    print("\nDone. Files to submit to GEM:")
    print("  openquake/hazardlib/gsim/bayless_somerville_2024.py")
    print("  openquake/hazardlib/tests/gsim/bayless_somerville_2024_test.py")
    print("  openquake/hazardlib/tests/gsim/data/BS24/BS24_CRATONIC.csv")
    print("  openquake/hazardlib/tests/gsim/data/BS24/BS24_NONCRATONIC.csv")
